# Generated by Django 4.2.23 on 2025-08-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.IntegerField(max_length=100),
        ),
    ]
